Update to latest skia and some improvements
adobe/svg-native-viewer pull request #113
Opened 2020-07-23 17:27 UTC by sunflowerdeath

Hello, I wanted to use you library but I have latest stable version of skia (m85), so I updated the code. It required me to enable  c++14 and to fix some minor API changes. Also, I added cmake flag `SKIA_SOURCE_DIR` that is similar to  `SKIA_LIBRARY_PATH`, that allows to specify location of Skia's sources when it is not in the `third_party` directory.

Also, I moved all public headers (including ports) into `include/svgnative` directory. This is good practice that is used by many modern cpp libraries, for example: https://github.com/fmtlib/fmt/tree/master/include/fmt, https://github.com/glfw/glfw/tree/master/include/GLFW, https://github.com/gabime/spdlog/tree/v1.x/include/spdlog
This helps to understand to which library header belong and helps avoid name conflicts (`#include "SVGDocument.h"` => `#include "svgnative/SVGDocument.h"`).

2020-08-30 08:36 UTC, dirkschulze requested changes
Thanks a lot for your contributions @sunflowerdeath and sorry for the delay in review. I like the changes. There are some requirements force by other projects that make it difficult to do some of the file moves. See inline comments.

2020-08-30 08:36 UTC, dirkschulze commented on svgnative/CMakeLists.txt
> +set(CMAKE_CXX_STANDARD 14)
It is a project requirement, due to other projects, to support C++ 11. Sadly, we can not change it to 14 at this point.

2020-08-30 08:36 UTC, dirkschulze commented on svgnative/CMakeLists.txt
> +    src/ports/string/StringSVGRenderer.cpp
Leaving the ports separate of the actual source was a requirement by other projects. I agree that it is odd, but I need to check if these requirements are still relevant. Could you leave the ports/ folder in root for now?

2020-08-30 08:36 UTC, dirkschulze commented on svgnative/example/testC/TestMain.c
> +#include "svgnative/SVGNativeCWrapper.h"
I agree that it is a good idea to move the includes.

2020-09-30 14:19 UTC, dirkschulze commented
@sunflowerdeath I see that Skia indeed requires a C++14 compatible compiler. IMO we should only require C++14 when the Skia port is enabled.

You patch looks great otherwise. Let me know if you get the time to do the necessary change. Otherwise I can do it on top of your changes as well.

2020-09-30 22:12 UTC, sunflowerdeath commented
> we should only require C++14 when the Skia port is enabled.
This is very good idea.

> Let me know if you get the time to do the necessary change. Otherwise I can do it on top of your changes as well.
Currently I might not have time for it, so if you could do it, it woud be great.

2020-10-24 19:32 UTC, dirkschulze commented
Covered by #118 now. @sunflowerdeath, could you take a look at the changes on that PR please?

2020-10-24 19:32 UTC, closed without merging